In [5]:
# 创建数组
import numpy as np 
a = np.array([1, 2, 3, 4, 5]) 
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a)
print(b)
b[1,1]=10
print(a.shape)
print(b.shape)
print(a.dtype)
print(b.dtype)
print(b)


[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(5,)
(3, 3)
int32
int32
[[ 1  2  3]
 [ 4 10  6]
 [ 7  8  9]]


In [9]:
# 结构数组
import numpy as np
'''
在 NumPy 中是用 dtype 定义的结构类型，
然后在定义数组的时候，用 array 中指定了结构数组的类型 dtype=persontype，这样你就可以自由地使用自定义的 persontype 了。
'''
persontype = np.dtype({
    'names':['name', 'age', 'chinese', 'math', 'english'],
    'formats':['S32','i', 'i', 'i', 'f']})
peoples = np.array([("ZhangFei",32,75,100, 90),("GuanYu",24,85,96,88.5),
       ("ZhaoYun",28,85,92,96.5),("HuangZhong",29,65,85,100)],
    dtype=persontype)
print(peoples)
ages = peoples[:]['age']
chineses = peoples[:]['chinese']
maths = peoples[:]['math']
englishs = peoples[:]['english']
print('ages:',ages)
print(np.mean(ages))
print('chineses:',chineses)
print(np.mean(chineses))
print('maths:',maths)
print(np.mean(maths))
print('englishs:',englishs)
print(np.mean(englishs))

[(b'ZhangFei', 32, 75, 100,  90. ) (b'GuanYu', 24, 85,  96,  88.5)
 (b'ZhaoYun', 28, 85,  92,  96.5) (b'HuangZhong', 29, 65,  85, 100. )]
ages: [32 24 28 29]
28.25
chineses: [75 85 85 65]
77.5
maths: [100  96  92  85]
93.25
englishs: [ 90.   88.5  96.5 100. ]
93.75


In [12]:
# NumPy 中很多 ufunc 函数计算速度非常快，因为都是采用 C 语言实现的。

x1 = np.arange(1,11,2)
x2 = np.linspace(1,9,5)
print(x1)
print(x2)
# 加、减、乘、除、求 n 次方、取余数
print(np.add(x1, x2))
print(np.subtract(x1, x2))
print(np.multiply(x1, x2))
print(np.divide(x1, x2))
print(np.power(x1, x2))
print(np.remainder(x1, x2))

[1 3 5 7 9]
[1. 3. 5. 7. 9.]
[ 2.  6. 10. 14. 18.]
[0. 0. 0. 0. 0.]
[ 1.  9. 25. 49. 81.]
[1. 1. 1. 1. 1.]
[1.00000000e+00 2.70000000e+01 3.12500000e+03 8.23543000e+05
 3.87420489e+08]
[0. 0. 0. 0. 0.]


In [13]:
# 计数组 / 矩阵中的最大值函数 amax()，最小值函数 amin()
import numpy as np
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
'''
axis = 0 代表对横轴操作，也就是第0轴；
axis = 1 代表对纵轴操作，也就是第1轴；

1,2,3
4,5,6
7,8,9
amin(a,0) 是延着 axis=0 轴的最小值
axis=0 轴是把元素看成了 [1,4,7], [2,5,8], [3,6,9] 三个元素，所以最小值为 [1,2,3]，
amin(a,1) 是延着 axis=1 轴的最小值
axis=1 轴是把元素看成了 [1,2,3], [4,5,6], [7,8,9] 三个元素，所以最小值为 [1,4,7]。
'''
print(np.amin(a))
print(np.amin(a,0))
print(np.amin(a,1))
print(np.amax(a))
print(np.amax(a,0))
print(np.amax(a,1))

1
[1 2 3]
[1 4 7]
9
[7 8 9]
[3 6 9]


In [15]:
# 统计最大值与最小值之差

a = np.array([[1,2,3], [4,5,6], [7,8,9]])
'''
ptp(a,0) 统计的是沿着 axis=0 轴的最大值与最小值之差，
即 7-1=6（当然 8-2=6,9-3=6，第三行减去第一行的 ptp 差均为 6）
ptp(a,1) 统计的是沿着 axis=1 轴的最大值与最小值之差，
即 3-1=2（当然 6-4=2, 9-7=2，即第三列与第一列的 ptp 差均为 2）
'''
print(np.ptp(a))
print(np.ptp(a,0))
print(np.ptp(a,1))

8
[6 6 6]
[2 2 2]


In [18]:
# 统计数组的百分位数 percentile()
a = np.array([[1,2,3], [4,5,6], [7,8,100]])
'''
percentile() 代表着第 p 个百分位数，这里 p 的取值范围是 0-100，
如果 p=0，那么就是求最小值，
如果 p=50 就是50%分位数字，中位数
如果 p=100 就是求最大值。
同样你也可以求得在 axis=0 和 axis=1 两个轴上的 p% 的百分位数。
'''
print(np.percentile(a, 50))
print(np.percentile(a, 50, axis=0))
print(np.percentile(a, 50, axis=1))

5.0
[4. 5. 6.]
[2. 5. 8.]


In [21]:
# 统计数组中的中位数 median()、平均数 mean()
a = np.array([[1,2,3], [4,5,6], [7,8,100]])
#求中位数
print(np.median(a))
print(np.median(a, axis=0))
print(np.median(a, axis=1))
#求平均数
print(np.mean(a))
print(np.mean(a, axis=0))
print(np.mean(a, axis=1))

5.0
[4. 5. 6.]
[2. 5. 8.]
15.11111111111111
[ 4.          5.         36.33333333]
[ 2.          5.         38.33333333]


In [25]:
# 加权平均数
'''
average() 函数可以求加权平均，加权平均的意思就是每个元素可以设置个权重，
默认情况下每个元素的权重是相同的，
所以 np.average(a)=(1+2+3+4)/4=2.5，
你也可以指定权重数组 wts=[1,2,3,4]，
这样加权平均 np.average(a,weights=wts)=(1*1+2*2+3*3+4*4)/(1+2+3+4)=3.0。
'''

a = np.array([1,2,3,4])
wts = np.array([1,2,3,4])
print(np.average(a))
print(np.average(a,weights=wts))

2.5
3.0


In [26]:
# 统计数组中的标准差 std()、方差 var()

a = np.array([1,2,3,4])
print(np.std(a))
print(np.var(a))

1.118033988749895
1.25


In [30]:
'''
排序算法在 NumPy 中实现起来其实非常简单，一条语句就可以搞定。
这里你可以使用 sort 函数，sort(a, axis=-1, kind=‘quicksort’, order=None)，
默认情况下使用的是快速排序；
在 kind 里，可以指定 quicksort、mergesort、heapsort 分别表示快速排序、合并排序、堆排序。
同样 axis 默认是 -1，
即沿着数组的最后一个轴进行排序，
也可以取不同的 axis 轴，或者 axis=None 代表采用扁平化的方式作为一个向量进行排序。
另外 order 字段，对于结构化的数组可以指定按照某个字段进行排序。
'''
a = np.array([[4,3,2],[2,4,1]])
print(np.sort(a),end='\n\n')
print(np.sort(a, axis=None))
print(np.sort(a, axis=0))  
print(np.sort(a, axis=1))

[[2 3 4]
 [1 2 4]]

[1 2 2 3 4 4]
[[2 3 1]
 [4 4 2]]
[[2 3 4]
 [1 2 4]]


In [32]:
from IPython.display import Image
from IPython.core.display import HTML 
Image(url= "https://static001.geekbang.org/resource/image/7b/66/7ba74ca7776ac29a5dc94c272d72ff66.jpg")
    