In [17]:
'''
https://crossincode.com/vip/homework/210/

任务1：利用 numpy 读取 csv 文件数据，命名为 iris，并以 ndarry 形式展示出来（阅读参考文章①）

https://blog.csdn.net/u012413551/article/details/87890989
-- str 参数，字符串处理 (默认情况下，数据被认为是float类型)
-- skiprows = 1  跳过首行 
-- usecols参数介绍一个元组，元组里面用列索引来指定输入特定的列。
-- -- usecols = (0,2) 第一、第二、第三列
-- -- 指定顺序：

'''
import numpy as np
import csv
p = r'.\iris.csv'
with open(p,encoding = 'utf-8') as f:
#     iris = np.loadtxt(f,str,delimiter = ",")
    iris = np.loadtxt(f,delimiter = ",")

iris[:5] # 前5行

# data[:5,1] # 取前5行的第2列
# print(iris[4,2])  #取具体的第5行第3列  IndexError: too many indices for array

array([5.1, 4.9, 4.7, 4.6, 5. ])

In [25]:
'''
任务2  找出原数据中最小值和最大值出现的位置（任务提示：numpy 中 argmax 和 argmin 函数可以定位到最大值和最小值的索引位置。阅读参考文章②）
https://blog.csdn.net/lanchunhui/article/details/50044417
'''
# print(iris)
# iris_list = iris.tolist() ndarray 转list
# print(len(iris_list))
max_index = np.argmax(iris)
print('原数据中最大值位置：',max_index)
min_index = np.argmin(iris)
print('原数据中最小值位置：',min_index)


原数据中最大值位置： 131
原数据中最小值位置： 13


In [24]:
'''
任务3：利用 numpy 找出花萼最小值与最大值（阅读参考文章②）
'''
print('原数据中最大值：',max(iris))
min_index = np.argmin(iris)
print('原数据中最小值：',min(iris))


原数据中最大值： 7.9
原数据中最小值： 4.3


In [26]:
'''
任务4：将 iris 原数据进行从小到大排序，并以 ndarray 形式展示出来
（任务提示：排序函数为 sort。阅读参考文章③）
https://www.jb51.net/article/52730.htm
'''
iris.sort()
iris


array([4.3, 4.4, 4.4, 4.4, 4.5, 4.6, 4.6, 4.6, 4.6, 4.7, 4.7, 4.8, 4.8,
       4.8, 4.8, 4.8, 4.9, 4.9, 4.9, 4.9, 4.9, 4.9, 5. , 5. , 5. , 5. ,
       5. , 5. , 5. , 5. , 5. , 5. , 5.1, 5.1, 5.1, 5.1, 5.1, 5.1, 5.1,
       5.1, 5.1, 5.2, 5.2, 5.2, 5.2, 5.3, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4,
       5.5, 5.5, 5.5, 5.5, 5.5, 5.5, 5.5, 5.6, 5.6, 5.6, 5.6, 5.6, 5.6,
       5.7, 5.7, 5.7, 5.7, 5.7, 5.7, 5.7, 5.7, 5.8, 5.8, 5.8, 5.8, 5.8,
       5.8, 5.8, 5.9, 5.9, 5.9, 6. , 6. , 6. , 6. , 6. , 6. , 6.1, 6.1,
       6.1, 6.1, 6.1, 6.1, 6.2, 6.2, 6.2, 6.2, 6.3, 6.3, 6.3, 6.3, 6.3,
       6.3, 6.3, 6.3, 6.3, 6.4, 6.4, 6.4, 6.4, 6.4, 6.4, 6.4, 6.5, 6.5,
       6.5, 6.5, 6.5, 6.6, 6.6, 6.7, 6.7, 6.7, 6.7, 6.7, 6.7, 6.7, 6.7,
       6.8, 6.8, 6.8, 6.9, 6.9, 6.9, 6.9, 7. , 7.1, 7.2, 7.2, 7.2, 7.3,
       7.4, 7.6, 7.7, 7.7, 7.7, 7.7, 7.9])

In [27]:
max_index = np.argmax(iris)
print('原数据中最大值位置：',max_index)

原数据中最大值位置： 149


In [34]:
'''
任务5 去除该组数据中的重复值（任务提示：去重函数为 np.unique()。阅读参考文章④）
https://blog.csdn.net/yangyuwen_yang/article/details/79193770
'''
# 对于一维数组或者列表，unique函数去除其中重复的元素，并按元素由大到小返回一个新的无元素重复的元组

u_iris = np.unique(iris)
print('去重后的：', u_iris)
print('原始数据：', iris)

# c,s=np.unique(b,return_index=True) 
# return_index=True表示返回新列表元素在旧列表中的位置，并以列表形式储存在s中。

# c,s = np.unique(iris,return_index=True )
# print(c)
# print(s)

# a, s,p = np.unique(A, return_index=True, return_inverse=True)
# return_inverse=True 表示返回旧列表元素在新列表中的位置，并以列表形式储存在p中
print('-------------')
c,s, p = np.unique(iris,return_index=True,return_inverse=True )
# print('去重后的：',c)
print('在旧列表中的位置：',s)
print('在新列表中的位置：',p)

去重后的： [4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3 5.4 5.5 5.6 5.7 5.8 5.9 6.
 6.1 6.2 6.3 6.4 6.5 6.6 6.7 6.8 6.9 7.  7.1 7.2 7.3 7.4 7.6 7.7 7.9]
原始数据： [4.3 4.4 4.4 4.4 4.5 4.6 4.6 4.6 4.6 4.7 4.7 4.8 4.8 4.8 4.8 4.8 4.9 4.9
 4.9 4.9 4.9 4.9 5.  5.  5.  5.  5.  5.  5.  5.  5.  5.  5.1 5.1 5.1 5.1
 5.1 5.1 5.1 5.1 5.1 5.2 5.2 5.2 5.2 5.3 5.4 5.4 5.4 5.4 5.4 5.4 5.5 5.5
 5.5 5.5 5.5 5.5 5.5 5.6 5.6 5.6 5.6 5.6 5.6 5.7 5.7 5.7 5.7 5.7 5.7 5.7
 5.7 5.8 5.8 5.8 5.8 5.8 5.8 5.8 5.9 5.9 5.9 6.  6.  6.  6.  6.  6.  6.1
 6.1 6.1 6.1 6.1 6.1 6.2 6.2 6.2 6.2 6.3 6.3 6.3 6.3 6.3 6.3 6.3 6.3 6.3
 6.4 6.4 6.4 6.4 6.4 6.4 6.4 6.5 6.5 6.5 6.5 6.5 6.6 6.6 6.7 6.7 6.7 6.7
 6.7 6.7 6.7 6.7 6.8 6.8 6.8 6.9 6.9 6.9 6.9 7.  7.1 7.2 7.2 7.2 7.3 7.4
 7.6 7.7 7.7 7.7 7.7 7.9]
-------------
去重后的： [4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3 5.4 5.5 5.6 5.7 5.8 5.9 6.
 6.1 6.2 6.3 6.4 6.5 6.6 6.7 6.8 6.9 7.  7.1 7.2 7.3 7.4 7.6 7.7 7.9]
在旧列表中的位置： [  0   1   4   5   9  11  16  22  32  41  45  46  52  59  65  73

In [37]:
'''
任务6：请利用 numpy 计算出该组花萼的平均长度（任务提示：平均函数为 np.mean()。阅读参考文章⑤）
https://blog.csdn.net/andybegin/article/details/84033216

'''

# 计算整个数据的平均值
print(iris.mean()) # 3

# 计算每一列的平均值
print(iris.mean(axis=0)) 

# 计算每一行的平均值
# print(iris.mean(axis=1))  # IndexError: tuple index out of range


5.843333333333334
5.843333333333334


In [38]:
'''
任务7：用numpy计算出该组数据的标准差和方差，并得出相关结论（任务提示：标准差可以衡量数据的波动性。阅读参考文章⑥）
https://blog.csdn.net/Dawn510/article/details/89336650


'''

# 均值
print(np.mean(iris))
 
# 方差
print(np.var(iris))
 
# 标准差
print(np.std(iris))

5.843333333333334
0.6811222222222223
0.8253012917851409


In [ ]:
结论：标准差越小，数据的波动越小。

In [42]:
'''
任务8：求出所有花瓣累积总和（阅读参考文章⑦）
https://blog.csdn.net/wangxiao7474/article/details/78867390
sum() 没有axis参数表示全部数据相加
axis=0，表示按列相加
axis=1，表示按行相加

'''

print('所有花瓣累积总和:', np.sum(iris))



所有花瓣累积总和: 876.5


In [43]:
'''
任务9：对已排序的 iris 数据进行累积求和运算
（任务提示：累积求和与求和有区别，累积求和是前几个数相加成新的元素从而组成新的数组。阅读参考文章⑧⑨）

https://blog.csdn.net/weixin_43486780/article/details/104692759

语法：numpy.cumsum(a, axis=None, dtype=None, out=None)
numpy中的cumsum函数按指定轴累加求和，返回中间结果组成的数组，在求累积分布时用到，这里是一维所以并没有指定轴

'''

cumsum_i = np.cumsum(iris, axis = 0)

cumsum_i

array([  4.3,   8.7,  13.1,  17.5,  22. ,  26.6,  31.2,  35.8,  40.4,
        45.1,  49.8,  54.6,  59.4,  64.2,  69. ,  73.8,  78.7,  83.6,
        88.5,  93.4,  98.3, 103.2, 108.2, 113.2, 118.2, 123.2, 128.2,
       133.2, 138.2, 143.2, 148.2, 153.2, 158.3, 163.4, 168.5, 173.6,
       178.7, 183.8, 188.9, 194. , 199.1, 204.3, 209.5, 214.7, 219.9,
       225.2, 230.6, 236. , 241.4, 246.8, 252.2, 257.6, 263.1, 268.6,
       274.1, 279.6, 285.1, 290.6, 296.1, 301.7, 307.3, 312.9, 318.5,
       324.1, 329.7, 335.4, 341.1, 346.8, 352.5, 358.2, 363.9, 369.6,
       375.3, 381.1, 386.9, 392.7, 398.5, 404.3, 410.1, 415.9, 421.8,
       427.7, 433.6, 439.6, 445.6, 451.6, 457.6, 463.6, 469.6, 475.7,
       481.8, 487.9, 494. , 500.1, 506.2, 512.4, 518.6, 524.8, 531. ,
       537.3, 543.6, 549.9, 556.2, 562.5, 568.8, 575.1, 581.4, 587.7,
       594.1, 600.5, 606.9, 613.3, 619.7, 626.1, 632.5, 639. , 645.5,
       652. , 658.5, 665. , 671.6, 678.2, 684.9, 691.6, 698.3, 705. ,
       711.7, 718.4,

In [47]:
'''
任务10：统计花萼长度比平均值 5.84 高的有多少（任务提示：例如 (arr>1).sum() 可统计大于1的个数）

'''

print('花萼长度比平均值高的有：',(iris > np.mean(iris)).sum())

花萼长度比平均值高的有： 70
