In [1]:
import numpy as np

alice = [99,101,103]
bob=[110,108,105]
tim=[90,88,85]

slaries = np.array([alice,bob,tim])
taxaction = np.array([[0.2,0.25,0.22],[0.4,0.5,0.5],[0.1,0.2,0.1]])

max_income = np.max(slaries-slaries*taxaction)
max_income 

81.0

In [2]:
slaries-slaries*taxaction

array([[79.2 , 75.75, 80.34],
       [66.  , 54.  , 52.5 ],
       [81.  , 70.4 , 76.5 ]])

In [3]:
a = np.array([1,2,3])
b = np.array([[2,3,4],[3,4,5]])
print(a+b)
print(b-a)

[[3 5 7]
 [4 6 8]]
[[1 1 1]
 [2 2 2]]


In [4]:
c = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [5]:
# NumPy 切片和索引
# 第三列
c[: ,2]

array([ 3,  7, 11])

In [6]:
# 第2行开始
c[1:,:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [27]:
# 第2行开始，如果是所有列，后面要不要 : 都一样
c[1:, ]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [30]:
#  numpy 中的 broadcasting 
#  https://www.cnblogs.com/pied/p/8288856.html

import numpy as np

a = np.arange(12)
b = a.reshape(3,2,2)

c = np.arange(4)
d = c.reshape(2, 2)

e = np.arange(2)

print('b--------\n',b)
print('d--------\n',d)
print('d+b----------------\n', d+b)

print('e--------\n',e)
print ('e+b\n',e+b)

b--------
 [[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]
d--------
 [[0 1]
 [2 3]]
d+b----------------
 [[[ 0  2]
  [ 4  6]]

 [[ 4  6]
  [ 8 10]]

 [[ 8 10]
  [12 14]]]
e--------
 [0 1]
e+b
 [[[ 0  2]
  [ 2  4]]

 [[ 4  6]
  [ 6  8]]

 [[ 8 10]
  [10 12]]]


In [37]:
d1 = np.array([[[1,2,3,4],[2,3,4,5],[3,4,5,6]],[[1,2,4,6],[2,3,5,7],[3,4,6,9]]])
print('d-----\n',d1)
print('dim---------\n',d1.ndim)
print('shape---------\n',d1.shape)

d-----
 [[[1 2 3 4]
  [2 3 4 5]
  [3 4 5 6]]

 [[1 2 4 6]
  [2 3 5 7]
  [3 4 6 9]]]
dim---------
 3
shape---------
 (2, 3, 4)


In [38]:
a = np.array([1,2,3,4],dtype = np.int16)
print(a)
print(a.dtype)

[1 2 3 4]
int16


In [43]:
dataScientist = [130,132,137]
productManager = [127,140,145]
designer = [118,118,127]
softwareEngineer = [129,131,137]

employees = np.array([dataScientist,productManager,designer,softwareEngineer])
employees

array([[130, 132, 137],
       [127, 140, 145],
       [118, 118, 127],
       [129, 131, 137]])

In [44]:
employees[0,::2]

array([130, 137])

In [46]:
employees.dtype

dtype('int32')

In [45]:
#  employees[0,::2]*1.1 等价于 np.array([130, 137]) * np.array([1.1, 1.1]) 
# 注意 乘以 浮点型的 1.111 之后也没有改变 employees 的dtype
employees[0, ::2] = employees[0, ::2]*1.1111
employees

array([[144, 132, 152],
       [127, 140, 145],
       [118, 118, 127],
       [129, 131, 137]])

In [47]:
employees.dtype

dtype('int32')

In [50]:

test1 = np.array([130, 137]) 
print(test1)
print(test1.dtype)
test1 = test1* np.array([1.1, 1.1]) 
print(test1)
print(test1.dtype)


[130 137]
int32
[143.  150.7]
float64


In [10]:
X = np.array([[1,0,0],[0,2,2],[3,0,0]])
X

array([[1, 0, 0],
       [0, 2, 2],
       [3, 0, 0]])

In [11]:
print(np.nonzero(X))

(array([0, 1, 1, 2], dtype=int64), array([0, 1, 2, 0], dtype=int64))


In [2]:
X = np.array([[42,40,41,43,44,43], # Hong Kong
              [30,31,29,29,29,30], # New york
              [8,13,31,11,11,9],  # Berlin
              [11,11,12,13,11,12]]) # Montreal
X

array([[42, 40, 41, 43, 44, 43],
       [30, 31, 29, 29, 29, 30],
       [ 8, 13, 31, 11, 11,  9],
       [11, 11, 12, 13, 11, 12]])

In [3]:
cities = np.array(['HongKong','Newyork','Berlin','Montreal'])
cities

array(['HongKong', 'Newyork', 'Berlin', 'Montreal'], dtype='<U8')

In [4]:
polluted = set(cities[np.nonzero(X > np.average(X))[0]])
polluted

{'Berlin', 'HongKong', 'Newyork'}

In [19]:
np.average(X)

24.333333333333332

In [8]:
X > np.average(X) # 判断 X 的元素哪些大于平均值

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [False, False,  True, False, False, False],
       [False, False, False, False, False, False]])

In [9]:
x1 = np.array([[ True,  True],
       [False, False]])
x1

array([[ True,  True],
       [False, False]])

In [10]:
np.nonzero(x1) 

(array([0, 0], dtype=int64), array([0, 1], dtype=int64))

In [11]:
np.nonzero(X > np.average(X)) # 用nonzero方法，得到大于平均值的行列索引

(array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2], dtype=int64),
 array([0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 2], dtype=int64))

In [37]:
np.nonzero(X > np.average(X))[0] # 取得行索引

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2], dtype=int64)

In [16]:
(cities[np.nonzero(X > np.average(X))[0]]) # 用行索引取得城市

array(['HongKong', 'HongKong', 'HongKong', 'HongKong', 'HongKong',
       'HongKong', 'Newyork', 'Newyork', 'Newyork', 'Newyork', 'Newyork',
       'Newyork', 'Berlin'], dtype='<U8')

In [17]:
set(cities[np.nonzero(X > np.average(X))[0]])  # 去重复

{'Berlin', 'HongKong', 'Newyork'}

In [18]:
X.shape

(4, 6)

In [26]:
np.nonzero([[[1,2],[0,0]],
            [[0,0],[0,0]]])

(array([0, 0], dtype=int64),
 array([0, 0], dtype=int64),
 array([0, 1], dtype=int64))

In [29]:
np.nonzero([1,0,2])

(array([0, 2], dtype=int64),)

In [31]:
np.nonzero([True,True,False,True])

(array([0, 1, 3], dtype=int64),)

In [36]:
np.nonzero([[[1,2,0],[0,0,3]],
            [[0,4,0],[0,5,0]]])

(array([0, 0, 0, 1, 1], dtype=int64),
 array([0, 0, 1, 0, 1], dtype=int64),
 array([0, 1, 2, 1, 1], dtype=int64))